name: Netlify Build Logs

on:
  push:
    branches:
      - main  # Or your main branch
  pull_request:
    branches:
      - main

jobs:
  netlify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Netlify CLI
      run: npm install -g netlify-cli

    - name: Trigger Netlify build
      run: |
        netlify deploy --prod --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Output Build Logs
      run: |
        echo "Netlify Build Logs"
